name: Deploy to Develop
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM Deps
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cd functions && yarn install
      - run: firebase deploy
  notify:
    name: notify
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
